# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chat_system.proto for package 'chat_system_proto'

require 'grpc'
require_relative './chat_system_pb'

module ChatSystemProto
  module ChatSystem
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chat_system_proto.ChatSystem'

      rpc :CreateApplication, ::ChatSystemProto::CreateApplicationRequest, ::ChatSystemProto::Application
      rpc :UpdateApplication, ::ChatSystemProto::UpdateApplicationRequest, ::ChatSystemProto::Application
      rpc :GetApplication, ::ChatSystemProto::GetApplicationRequest, ::ChatSystemProto::Application
      rpc :CreateChat, ::ChatSystemProto::CreateChatRequest, ::ChatSystemProto::Chat
      rpc :GetChats, ::ChatSystemProto::GetChatsRequest, ::ChatSystemProto::ChatsList
      rpc :CreateMessage, ::ChatSystemProto::CreateMessageRequest, ::ChatSystemProto::Message
      rpc :GetMessages, ::ChatSystemProto::GetMessagesRequest, ::ChatSystemProto::MessagesList
      rpc :SearchMessages, ::ChatSystemProto::SearchMessagesRequest, ::ChatSystemProto::MessagesList
    end

    Stub = Service.rpc_stub_class
  end
end
